# ~/.tmuxinator/dev.yml

name: dev
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - server:
      layout: bdae,196x52,0,0{118x52,0,0,0,77x52,119,0[77x39,119,0,4,77x12,119,40,5]}
      panes:
        - coreconsole:
          - dcm
          - cd es-fe-console-ui
          - clear
        - grunt:
          - dcm
          - cd es-fe-angular-ui
          - clear
        - karma:
          - dcm
          - cd es-fe-angular-ui
          - clear
  - build:
      layout: even-vertical
      panes:
        - build:
          - dcm
          - cd es-in-build
          - clear
        - vagrant:
          - dcm
          - cd es-onpremise-chef-solo
          - clear
  - dev:
      layout: even-vertical
      panes:
        - misc1: clear
        - misc2: clear
  - shell: clear
