#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# homebrew install should happen first
./homebrew/install.sh

# find the installers and run them iteratively
find . -name install.sh -not -path "./homebrew/*" | while read installer ; do sh -c "${installer}" ; done
