#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# homebrew install should happen first
./homebrew/install.sh

# find the installers and run them iteratively
find . -name install.sh -not -path "./homebrew/*" | while read installer ; do sh -c "${installer}" ; done
