alias reload!='. ~/.zshrc'
alias h='cd ~/'
alias dev='cd ~/Development/Dell/sources'
alias dcm-build='./esbuild.sh --clean --install --bundle'
alias dcm-buildlaunch='./esbuild.sh --clean --install --bundle && ./eslaunch.sh -v --pretest'
alias dcm-launch='./eslaunch.sh -v --pretest'
alias weather='curl wttr.in/55410'
